name: PR Title Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  sheriff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Validate PR title
        uses: teneplaysofficial/sheriff@fe16e6cbcf9d1db3523f7f0f63cfba59db59a5f6 # v5
